name: Deploy to k8s
concurrency: 
  group: ${{github.ref_name}}
  cancel-in-progress: true
on:
  workflow_dispatch: 
permissions: 
  contents: read
env:
  CONTAINER_REGISTRY: ghcr.io
jobs:
  start-k8s:
    if: ${{1==2}}
    runs-on: ubuntu-latest
    outputs:
      cluster-id: ${{steps.create-cluster.outputs.cluster-id}}
      kube-config64: ${{steps.create-cluster.outputs.kube-config64}}
      cluster-ip: ${{steps.create-cluster.outputs.cluster-ip}}
    steps:
      - uses: sxtln/create-cluster@v0.1
        id: create-cluster
        with:
          api-key: ${{secrets.SXTLN_APIKEY}}
          node-count: 1
          node-type: b1
          cluster-name: "${{github.ref_name}}_${{github.run_id}}"
          
  build:
    permissions: 
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and push container
        shell: bash
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          IMAGE="${CONTAINER_REGISTRY}/${{github.repository}}:${SHORT_HASH}"
          echo building container: $IMAGE
          docker build -t $IMAGE -f Dockerfile .
          docker login --username=${{github.actor}} --password=${{secrets.GITHUB_TOKEN}} ${{env.CONTAINER_REGISTRY}}
          docker push $IMAGE
